import { DM_Sans, Playfair_Display, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable:"--font-roboto",
  subsets:["latin"],
})
const sansDM = DM_Sans({
  variable:"--font-dm-sans",
  subsets:["latin"],
  
})

const playFair = Playfair_Display({
  variable:"--font-play-fair",
  subsets:["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` h-full antialiased`}
    >
      <body className={`${sansDM.className} min-h-full flex flex-col`}>
        {children}</body>
    </html>
  );
}
